// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BloqueoProveedor generated by hbm2java
 */
public class BloqueoProveedor implements java.io.Serializable {

	private short idBloqueoProveedor;
	private String descripcion;
	private Set proveedors = new HashSet(0);

	public BloqueoProveedor() {
	}

	public BloqueoProveedor(short idBloqueoProveedor, String descripcion) {
		this.idBloqueoProveedor = idBloqueoProveedor;
		this.descripcion = descripcion;
	}

	public BloqueoProveedor(short idBloqueoProveedor, String descripcion,
			Set proveedors) {
		this.idBloqueoProveedor = idBloqueoProveedor;
		this.descripcion = descripcion;
		this.proveedors = proveedors;
	}

	public short getIdBloqueoProveedor() {
		return this.idBloqueoProveedor;
	}

	public void setIdBloqueoProveedor(short idBloqueoProveedor) {
		this.idBloqueoProveedor = idBloqueoProveedor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

}
