// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna implements java.io.Serializable {

	private int idComuna;
	private Region region;
	private String descripcion;
	private Set proveedorSucursals = new HashSet(0);
	private Set cotizacions = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Comuna() {
	}

	public Comuna(int idComuna, Region region, String descripcion) {
		this.idComuna = idComuna;
		this.region = region;
		this.descripcion = descripcion;
	}

	public Comuna(int idComuna, Region region, String descripcion,
			Set proveedorSucursals, Set cotizacions, Set usuarios) {
		this.idComuna = idComuna;
		this.region = region;
		this.descripcion = descripcion;
		this.proveedorSucursals = proveedorSucursals;
		this.cotizacions = cotizacions;
		this.usuarios = usuarios;
	}

	public int getIdComuna() {
		return this.idComuna;
	}

	public void setIdComuna(int idComuna) {
		this.idComuna = idComuna;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProveedorSucursals() {
		return this.proveedorSucursals;
	}

	public void setProveedorSucursals(Set proveedorSucursals) {
		this.proveedorSucursals = proveedorSucursals;
	}

	public Set getCotizacions() {
		return this.cotizacions;
	}

	public void setCotizacions(Set cotizacions) {
		this.cotizacions = cotizacions;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
