// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoProveedor generated by hbm2java
 */
public class EstadoProveedor implements java.io.Serializable {

	private short idEstadoProveedor;
	private String descripcion;
	private Set proveedors = new HashSet(0);

	public EstadoProveedor() {
	}

	public EstadoProveedor(short idEstadoProveedor, String descripcion) {
		this.idEstadoProveedor = idEstadoProveedor;
		this.descripcion = descripcion;
	}

	public EstadoProveedor(short idEstadoProveedor, String descripcion,
			Set proveedors) {
		this.idEstadoProveedor = idEstadoProveedor;
		this.descripcion = descripcion;
		this.proveedors = proveedors;
	}

	public short getIdEstadoProveedor() {
		return this.idEstadoProveedor;
	}

	public void setIdEstadoProveedor(short idEstadoProveedor) {
		this.idEstadoProveedor = idEstadoProveedor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

}
