// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private int folio;
	private MedioPago medioPago;
	private Proveedor proveedor;
	private String numeroTx;
	private String detallePago;
	private Boolean pagada;

	public Factura() {
	}

	public Factura(int folio, MedioPago medioPago, Proveedor proveedor) {
		this.folio = folio;
		this.medioPago = medioPago;
		this.proveedor = proveedor;
	}

	public Factura(int folio, MedioPago medioPago, Proveedor proveedor,
			String numeroTx, String detallePago, Boolean pagada) {
		this.folio = folio;
		this.medioPago = medioPago;
		this.proveedor = proveedor;
		this.numeroTx = numeroTx;
		this.detallePago = detallePago;
		this.pagada = pagada;
	}

	public int getFolio() {
		return this.folio;
	}

	public void setFolio(int folio) {
		this.folio = folio;
	}

	public MedioPago getMedioPago() {
		return this.medioPago;
	}

	public void setMedioPago(MedioPago medioPago) {
		this.medioPago = medioPago;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNumeroTx() {
		return this.numeroTx;
	}

	public void setNumeroTx(String numeroTx) {
		this.numeroTx = numeroTx;
	}

	public String getDetallePago() {
		return this.detallePago;
	}

	public void setDetallePago(String detallePago) {
		this.detallePago = detallePago;
	}

	public Boolean getPagada() {
		return this.pagada;
	}

	public void setPagada(Boolean pagada) {
		this.pagada = pagada;
	}

}
