// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * MarcaProveedor generated by hbm2java
 */
public class MarcaProveedor implements java.io.Serializable {

	private int idMarcaProveedor;
	private Marca marca;
	private Proveedor proveedor;
	private boolean certificado;

	public MarcaProveedor() {
	}

	public MarcaProveedor(int idMarcaProveedor, Marca marca,
			Proveedor proveedor, boolean certificado) {
		this.idMarcaProveedor = idMarcaProveedor;
		this.marca = marca;
		this.proveedor = proveedor;
		this.certificado = certificado;
	}

	public int getIdMarcaProveedor() {
		return this.idMarcaProveedor;
	}

	public void setIdMarcaProveedor(int idMarcaProveedor) {
		this.idMarcaProveedor = idMarcaProveedor;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public boolean isCertificado() {
		return this.certificado;
	}

	public void setCertificado(boolean certificado) {
		this.certificado = certificado;
	}

}
