// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca implements java.io.Serializable {

	private int idMarca;
	private TipoVehiculo tipoVehiculo;
	private String descripcion;
	private Set modelos = new HashSet(0);
	private Set marcaProveedors = new HashSet(0);

	public Marca() {
	}

	public Marca(int idMarca, TipoVehiculo tipoVehiculo, String descripcion) {
		this.idMarca = idMarca;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
	}

	public Marca(int idMarca, TipoVehiculo tipoVehiculo, String descripcion,
			Set modelos, Set marcaProveedors) {
		this.idMarca = idMarca;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
		this.modelos = modelos;
		this.marcaProveedors = marcaProveedors;
	}

	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	public TipoVehiculo getTipoVehiculo() {
		return this.tipoVehiculo;
	}

	public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
		this.tipoVehiculo = tipoVehiculo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getModelos() {
		return this.modelos;
	}

	public void setModelos(Set modelos) {
		this.modelos = modelos;
	}

	public Set getMarcaProveedors() {
		return this.marcaProveedors;
	}

	public void setMarcaProveedors(Set marcaProveedors) {
		this.marcaProveedors = marcaProveedors;
	}

}
