// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo implements java.io.Serializable {

	private int idModelo;
	private Marca marca;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public Modelo() {
	}

	public Modelo(int idModelo, Marca marca, String descripcion) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
	}

	public Modelo(int idModelo, Marca marca, String descripcion, Set vehiculos) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	public int getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(int idModelo) {
		this.idModelo = idModelo;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
