// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OfertaCotizacion generated by hbm2java
 */
public class OfertaCotizacion implements java.io.Serializable {

	private Long idOfertaCotizacion;
	private ProveedorSucursal proveedorSucursal;
	private Cotizacion cotizacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String comentarios;
	private Set adjudicacions = new HashSet(0);

	public OfertaCotizacion() {
	}

	public OfertaCotizacion(ProveedorSucursal proveedorSucursal,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion) {
		this.proveedorSucursal = proveedorSucursal;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public OfertaCotizacion(ProveedorSucursal proveedorSucursal,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion,
			String comentarios, Set adjudicacions) {
		this.proveedorSucursal = proveedorSucursal;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.comentarios = comentarios;
		this.adjudicacions = adjudicacions;
	}

	public Long getIdOfertaCotizacion() {
		return this.idOfertaCotizacion;
	}

	public void setIdOfertaCotizacion(Long idOfertaCotizacion) {
		this.idOfertaCotizacion = idOfertaCotizacion;
	}

	public ProveedorSucursal getProveedorSucursal() {
		return this.proveedorSucursal;
	}

	public void setProveedorSucursal(ProveedorSucursal proveedorSucursal) {
		this.proveedorSucursal = proveedorSucursal;
	}

	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public Set getAdjudicacions() {
		return this.adjudicacions;
	}

	public void setAdjudicacions(Set adjudicacions) {
		this.adjudicacions = adjudicacions;
	}

}
