// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private int idPais;
	private String descripcion;
	private Set regions = new HashSet(0);

	public Pais() {
	}

	public Pais(int idPais, String descripcion) {
		this.idPais = idPais;
		this.descripcion = descripcion;
	}

	public Pais(int idPais, String descripcion, Set regions) {
		this.idPais = idPais;
		this.descripcion = descripcion;
		this.regions = regions;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRegions() {
		return this.regions;
	}

	public void setRegions(Set regions) {
		this.regions = regions;
	}

}
