// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private Integer idProveedor;
	private BloqueoProveedor bloqueoProveedor;
	private EstadoProveedor estadoProveedor;
	private String rut;
	private String razonSocial;
	private String nombreFantasia;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String fax;
	private String correo;
	private String web;
	private String fotos;
	private String textoHtml;
	private Float latitud;
	private Float longitud;
	private Date fechaCreacion;
	private Set marcaProveedors = new HashSet(0);
	private Set facturas = new HashSet(0);
	private Set proveedorSucursals = new HashSet(0);

	public Proveedor() {
	}

	public Proveedor(BloqueoProveedor bloqueoProveedor,
			EstadoProveedor estadoProveedor) {
		this.bloqueoProveedor = bloqueoProveedor;
		this.estadoProveedor = estadoProveedor;
	}

	public Proveedor(BloqueoProveedor bloqueoProveedor,
			EstadoProveedor estadoProveedor, String rut, String razonSocial,
			String nombreFantasia, String direccion, String telefono1,
			String telefono2, String fax, String correo, String web,
			String fotos, String textoHtml, Float latitud, Float longitud,
			Date fechaCreacion, Set marcaProveedors, Set facturas,
			Set proveedorSucursals) {
		this.bloqueoProveedor = bloqueoProveedor;
		this.estadoProveedor = estadoProveedor;
		this.rut = rut;
		this.razonSocial = razonSocial;
		this.nombreFantasia = nombreFantasia;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.fax = fax;
		this.correo = correo;
		this.web = web;
		this.fotos = fotos;
		this.textoHtml = textoHtml;
		this.latitud = latitud;
		this.longitud = longitud;
		this.fechaCreacion = fechaCreacion;
		this.marcaProveedors = marcaProveedors;
		this.facturas = facturas;
		this.proveedorSucursals = proveedorSucursals;
	}

	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	public BloqueoProveedor getBloqueoProveedor() {
		return this.bloqueoProveedor;
	}

	public void setBloqueoProveedor(BloqueoProveedor bloqueoProveedor) {
		this.bloqueoProveedor = bloqueoProveedor;
	}

	public EstadoProveedor getEstadoProveedor() {
		return this.estadoProveedor;
	}

	public void setEstadoProveedor(EstadoProveedor estadoProveedor) {
		this.estadoProveedor = estadoProveedor;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getNombreFantasia() {
		return this.nombreFantasia;
	}

	public void setNombreFantasia(String nombreFantasia) {
		this.nombreFantasia = nombreFantasia;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getFotos() {
		return this.fotos;
	}

	public void setFotos(String fotos) {
		this.fotos = fotos;
	}

	public String getTextoHtml() {
		return this.textoHtml;
	}

	public void setTextoHtml(String textoHtml) {
		this.textoHtml = textoHtml;
	}

	public Float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Float latitud) {
		this.latitud = latitud;
	}

	public Float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Float longitud) {
		this.longitud = longitud;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set getMarcaProveedors() {
		return this.marcaProveedors;
	}

	public void setMarcaProveedors(Set marcaProveedors) {
		this.marcaProveedors = marcaProveedors;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getProveedorSucursals() {
		return this.proveedorSucursals;
	}

	public void setProveedorSucursals(Set proveedorSucursals) {
		this.proveedorSucursals = proveedorSucursals;
	}

}
