// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProveedorSucursalUsuario generated by hbm2java
 */
public class ProveedorSucursalUsuario implements java.io.Serializable {

	private Integer idProveedorSucursalUsuario;
	private ProveedorSucursal proveedorSucursal;
	private Rol rol;
	private Usuario usuario;
	private String rut;
	private String correo;
	private String telefono;

	public ProveedorSucursalUsuario() {
	}

	public ProveedorSucursalUsuario(ProveedorSucursal proveedorSucursal,
			Rol rol, Usuario usuario) {
		this.proveedorSucursal = proveedorSucursal;
		this.rol = rol;
		this.usuario = usuario;
	}

	public ProveedorSucursalUsuario(ProveedorSucursal proveedorSucursal,
			Rol rol, Usuario usuario, String rut, String correo, String telefono) {
		this.proveedorSucursal = proveedorSucursal;
		this.rol = rol;
		this.usuario = usuario;
		this.rut = rut;
		this.correo = correo;
		this.telefono = telefono;
	}

	public Integer getIdProveedorSucursalUsuario() {
		return this.idProveedorSucursalUsuario;
	}

	public void setIdProveedorSucursalUsuario(Integer idProveedorSucursalUsuario) {
		this.idProveedorSucursalUsuario = idProveedorSucursalUsuario;
	}

	public ProveedorSucursal getProveedorSucursal() {
		return this.proveedorSucursal;
	}

	public void setProveedorSucursal(ProveedorSucursal proveedorSucursal) {
		this.proveedorSucursal = proveedorSucursal;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
