// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProveedorSucursal generated by hbm2java
 */
public class ProveedorSucursal implements java.io.Serializable {

	private Integer idProveedorSucursal;
	private Comuna comuna;
	private Combustible combustible;
	private Proveedor proveedor;
	private String descripcion;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String fax;
	private String correo;
	private String web;
	private String fotos;
	private String textoHtml;
	private Date fechaCreacion;
	private Set proveedorSucursalUsuarios = new HashSet(0);
	private Set proveedorSucursalServicios = new HashSet(0);
	private Set ofertaCotizacions = new HashSet(0);

	public ProveedorSucursal() {
	}

	public ProveedorSucursal(Comuna comuna, Proveedor proveedor,
			String descripcion, String direccion, Date fechaCreacion) {
		this.comuna = comuna;
		this.proveedor = proveedor;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.fechaCreacion = fechaCreacion;
	}

	public ProveedorSucursal(Comuna comuna, Combustible combustible,
			Proveedor proveedor, String descripcion, String direccion,
			String telefono1, String telefono2, String fax, String correo,
			String web, String fotos, String textoHtml, Date fechaCreacion,
			Set proveedorSucursalUsuarios, Set proveedorSucursalServicios,
			Set ofertaCotizacions) {
		this.comuna = comuna;
		this.combustible = combustible;
		this.proveedor = proveedor;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.fax = fax;
		this.correo = correo;
		this.web = web;
		this.fotos = fotos;
		this.textoHtml = textoHtml;
		this.fechaCreacion = fechaCreacion;
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
		this.proveedorSucursalServicios = proveedorSucursalServicios;
		this.ofertaCotizacions = ofertaCotizacions;
	}

	public Integer getIdProveedorSucursal() {
		return this.idProveedorSucursal;
	}

	public void setIdProveedorSucursal(Integer idProveedorSucursal) {
		this.idProveedorSucursal = idProveedorSucursal;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public Combustible getCombustible() {
		return this.combustible;
	}

	public void setCombustible(Combustible combustible) {
		this.combustible = combustible;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getFotos() {
		return this.fotos;
	}

	public void setFotos(String fotos) {
		this.fotos = fotos;
	}

	public String getTextoHtml() {
		return this.textoHtml;
	}

	public void setTextoHtml(String textoHtml) {
		this.textoHtml = textoHtml;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set getProveedorSucursalUsuarios() {
		return this.proveedorSucursalUsuarios;
	}

	public void setProveedorSucursalUsuarios(Set proveedorSucursalUsuarios) {
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

	public Set getProveedorSucursalServicios() {
		return this.proveedorSucursalServicios;
	}

	public void setProveedorSucursalServicios(Set proveedorSucursalServicios) {
		this.proveedorSucursalServicios = proveedorSucursalServicios;
	}

	public Set getOfertaCotizacions() {
		return this.ofertaCotizacions;
	}

	public void setOfertaCotizacions(Set ofertaCotizacions) {
		this.ofertaCotizacions = ofertaCotizacions;
	}

}
