// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private int idRegion;
	private Pais pais;
	private String descripcion;
	private Set comunas = new HashSet(0);

	public Region() {
	}

	public Region(int idRegion, Pais pais, String descripcion) {
		this.idRegion = idRegion;
		this.pais = pais;
		this.descripcion = descripcion;
	}

	public Region(int idRegion, Pais pais, String descripcion, Set comunas) {
		this.idRegion = idRegion;
		this.pais = pais;
		this.descripcion = descripcion;
		this.comunas = comunas;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getComunas() {
		return this.comunas;
	}

	public void setComunas(Set comunas) {
		this.comunas = comunas;
	}

}
