// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private short idRol;
	private String descripcion;
	private Set proveedorSucursalUsuarios = new HashSet(0);

	public Rol() {
	}

	public Rol(short idRol, String descripcion) {
		this.idRol = idRol;
		this.descripcion = descripcion;
	}

	public Rol(short idRol, String descripcion, Set proveedorSucursalUsuarios) {
		this.idRol = idRol;
		this.descripcion = descripcion;
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

	public short getIdRol() {
		return this.idRol;
	}

	public void setIdRol(short idRol) {
		this.idRol = idRol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProveedorSucursalUsuarios() {
		return this.proveedorSucursalUsuarios;
	}

	public void setProveedorSucursalUsuarios(Set proveedorSucursalUsuarios) {
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

}
