// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoTransmision generated by hbm2java
 */
public class TipoTransmision implements java.io.Serializable {

	private short idTipoTransmision;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public TipoTransmision() {
	}

	public TipoTransmision(short idTipoTransmision, String descripcion) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
	}

	public TipoTransmision(short idTipoTransmision, String descripcion,
			Set vehiculos) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	public short getIdTipoTransmision() {
		return this.idTipoTransmision;
	}

	public void setIdTipoTransmision(short idTipoTransmision) {
		this.idTipoTransmision = idTipoTransmision;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
