// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoVehiculo generated by hbm2java
 */
public class TipoVehiculo implements java.io.Serializable {

	private short idTipoVehiculo;
	private String descripcion;
	private Set proveedorSucursalServicios = new HashSet(0);
	private Set marcas = new HashSet(0);

	public TipoVehiculo() {
	}

	public TipoVehiculo(short idTipoVehiculo, String descripcion) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
	}

	public TipoVehiculo(short idTipoVehiculo, String descripcion,
			Set proveedorSucursalServicios, Set marcas) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
		this.proveedorSucursalServicios = proveedorSucursalServicios;
		this.marcas = marcas;
	}

	public short getIdTipoVehiculo() {
		return this.idTipoVehiculo;
	}

	public void setIdTipoVehiculo(short idTipoVehiculo) {
		this.idTipoVehiculo = idTipoVehiculo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProveedorSucursalServicios() {
		return this.proveedorSucursalServicios;
	}

	public void setProveedorSucursalServicios(Set proveedorSucursalServicios) {
		this.proveedorSucursalServicios = proveedorSucursalServicios;
	}

	public Set getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Set marcas) {
		this.marcas = marcas;
	}

}
