// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Traccion generated by hbm2java
 */
public class Traccion implements java.io.Serializable {

	private short idTraccion;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public Traccion() {
	}

	public Traccion(short idTraccion, String descripcion) {
		this.idTraccion = idTraccion;
		this.descripcion = descripcion;
	}

	public Traccion(short idTraccion, String descripcion, Set vehiculos) {
		this.idTraccion = idTraccion;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	public short getIdTraccion() {
		return this.idTraccion;
	}

	public void setIdTraccion(short idTraccion) {
		this.idTraccion = idTraccion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
