// default package
// Generated Feb 21, 2016 1:29:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Long idUsuario;
	private Comuna comuna;
	private String nombreusuario;
	private String contrasena;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String correo;
	private String telefono;
	private Date fechaCreacion;
	private boolean activo;
	private Set proveedorSucursalUsuarios = new HashSet(0);
	private Set vehiculos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Comuna comuna, String nombreusuario, String contrasena,
			Date fechaCreacion, boolean activo) {
		this.comuna = comuna;
		this.nombreusuario = nombreusuario;
		this.contrasena = contrasena;
		this.fechaCreacion = fechaCreacion;
		this.activo = activo;
	}

	public Usuario(Comuna comuna, String nombreusuario, String contrasena,
			String nombre, String apellidoPaterno, String apellidoMaterno,
			String correo, String telefono, Date fechaCreacion, boolean activo,
			Set proveedorSucursalUsuarios, Set vehiculos) {
		this.comuna = comuna;
		this.nombreusuario = nombreusuario;
		this.contrasena = contrasena;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correo = correo;
		this.telefono = telefono;
		this.fechaCreacion = fechaCreacion;
		this.activo = activo;
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
		this.vehiculos = vehiculos;
	}

	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set getProveedorSucursalUsuarios() {
		return this.proveedorSucursalUsuarios;
	}

	public void setProveedorSucursalUsuarios(Set proveedorSucursalUsuarios) {
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
