-- MySQL Script generated by MySQL Workbench
-- sáb 19 mar 2016 22:18:26 CLT
-- Model: New Model    Version: 1.1

-- Revision LHB

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pais` (
  `id_pais` INT NOT NULL,
  `descripcion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `region` (
  `id_region` INT NOT NULL,
  `id_pais` INT NOT NULL,
  `descripcion` VARCHAR(128) NOT NULL,
  `descripcion_breve` VARCHAR(8) NOT NULL,
  `orden` SMALLINT NOT NULL,
  PRIMARY KEY (`id_region`),
  CONSTRAINT `fk_region_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_region_pais1_idx` ON `region` (`id_pais` ASC);


-- -----------------------------------------------------
-- Table `comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comuna` (
  `id_comuna` INT NOT NULL,
  `id_region` INT NOT NULL,
  `descripcion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_comuna`),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`id_region`)
    REFERENCES `region` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comuna_region1_idx` ON `comuna` (`id_region` ASC);


-- -----------------------------------------------------
-- Table `tipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_vehiculo` (
  `id_tipo_vehiculo` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_tipo_vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marca` (
  `id_marca` INT NOT NULL,
  `id_tipo_vehiculo` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_marca`),
  CONSTRAINT `fk_marca_tipo_vehiculo1`
    FOREIGN KEY (`id_tipo_vehiculo`)
    REFERENCES `tipo_vehiculo` (`id_tipo_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_marca_tipo_vehiculo1_idx` ON `marca` (`id_tipo_vehiculo` ASC);


-- -----------------------------------------------------
-- Table `modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo` (
  `id_modelo` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_modelo`),
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_modelo_marca1_idx` ON `modelo` (`id_marca` ASC);


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `id_comuna` INT NOT NULL,
  `nombreusuario` VARCHAR(32) NOT NULL,
  `contrasena` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(32) NULL,
  `apellido_paterno` VARCHAR(32) NULL,
  `apellido_materno` VARCHAR(32) NULL,
  `correo` VARCHAR(64) NULL,
  `telefono` VARCHAR(32) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_comuna1`
    FOREIGN KEY (`id_comuna`)
    REFERENCES `comuna` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_comuna1_idx` ON `usuario` (`id_comuna` ASC);


-- -----------------------------------------------------
-- Table `combustible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `combustible` (
  `id_combustible` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_combustible`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_transmision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_transmision` (
  `id_tipo_transmision` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_tipo_transmision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `traccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traccion` (
  `id_traccion` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_traccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehiculo` (
  `id_vehiculo` BIGINT NOT NULL AUTO_INCREMENT,
  `id_usuario` BIGINT NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_combustible` SMALLINT NOT NULL,
  `id_tipo_transmision` SMALLINT NOT NULL,
  `id_traccion` SMALLINT NOT NULL,
  `patente` VARCHAR(8) NULL,
  `anio` SMALLINT NULL,
  `aire_acondicionado` TINYINT(1) NULL,
  `alza_vidrios` TINYINT(1) NULL,
  PRIMARY KEY (`id_vehiculo`),
  CONSTRAINT `fk_vehiculo_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_combustible1`
    FOREIGN KEY (`id_combustible`)
    REFERENCES `combustible` (`id_combustible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_tipo_transmision1`
    FOREIGN KEY (`id_tipo_transmision`)
    REFERENCES `tipo_transmision` (`id_tipo_transmision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_traccion1`
    FOREIGN KEY (`id_traccion`)
    REFERENCES `traccion` (`id_traccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vehiculo_modelo1_idx` ON `vehiculo` (`id_modelo` ASC);

CREATE INDEX `fk_vehiculo_usuario1_idx` ON `vehiculo` (`id_usuario` ASC);

CREATE INDEX `fk_vehiculo_combustible1_idx` ON `vehiculo` (`id_combustible` ASC);

CREATE INDEX `fk_vehiculo_tipo_transmision1_idx` ON `vehiculo` (`id_tipo_transmision` ASC);

CREATE INDEX `fk_vehiculo_traccion1_idx` ON `vehiculo` (`id_traccion` ASC);


-- -----------------------------------------------------
-- Table `cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizacion` (
  `id_cotizacion` BIGINT NOT NULL AUTO_INCREMENT,
  `id_servicio` INT NOT NULL,
  `id_comuna` INT NOT NULL,
  `id_vehiculo` BIGINT NOT NULL,
  `descripcion` TEXT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cotizacion`),
  CONSTRAINT `fk_cotizacion_servicio1`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizacion_comuna1`
    FOREIGN KEY (`id_comuna`)
    REFERENCES `comuna` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizacion_vehiculo1`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `vehiculo` (`id_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cotizacion_servicio1_idx` ON `cotizacion` (`id_servicio` ASC);

CREATE INDEX `fk_cotizacion_comuna1_idx` ON `cotizacion` (`id_comuna` ASC);

CREATE INDEX `fk_cotizacion_vehiculo1_idx` ON `cotizacion` (`id_vehiculo` ASC);


-- -----------------------------------------------------
-- Table `estado_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado_proveedor` (
  `id_estado_proveedor` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_estado_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloqueo_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloqueo_proveedor` (
  `id_bloqueo_proveedor` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_bloqueo_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `id_estado_proveedor` SMALLINT NOT NULL,
  `id_bloqueo_proveedor` SMALLINT NOT NULL,
  `rut` VARCHAR(16) NULL,
  `razon_social` VARCHAR(128) NULL,
  `nombre_fantasia` VARCHAR(128) NULL,
  `direccion_facturacion` VARCHAR(256) NULL,
  `web` VARCHAR(128) NULL,
  `texto_html` TEXT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  CONSTRAINT `fk_proveedor_estado_proveedor1`
    FOREIGN KEY (`id_estado_proveedor`)
    REFERENCES `estado_proveedor` (`id_estado_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_bloqueo_proveedor1`
    FOREIGN KEY (`id_bloqueo_proveedor`)
    REFERENCES `bloqueo_proveedor` (`id_bloqueo_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_estado_proveedor1_idx` ON `proveedor` (`id_estado_proveedor` ASC);

CREATE INDEX `fk_proveedor_bloqueo_proveedor1_idx` ON `proveedor` (`id_bloqueo_proveedor` ASC);

CREATE UNIQUE INDEX `idx_proveedor_rut` USING BTREE ON `proveedor` (`rut` ASC);


-- -----------------------------------------------------
-- Table `proveedor_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_sucursal` (
  `id_proveedor_sucursal` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `id_comuna` INT NOT NULL,
  `descripcion` VARCHAR(64) NOT NULL,
  `direccion` VARCHAR(256) NOT NULL,
  `telefono1` VARCHAR(16) NULL,
  `telefono2` VARCHAR(16) NULL,
  `fax` VARCHAR(16) NULL,
  `correo` VARCHAR(64) NULL,
  `fotos` VARCHAR(64) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `multimarca` TINYINT(1) NOT NULL DEFAULT 0,
  `latitud` FLOAT NULL,
  `longitud` FLOAT NULL,
  PRIMARY KEY (`id_proveedor_sucursal`),
  CONSTRAINT `fk_proveedor_sucursal_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proveedor` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_comuna1`
    FOREIGN KEY (`id_comuna`)
    REFERENCES `comuna` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sucursal_empresa_proveedor1_idx` ON `proveedor_sucursal` (`id_proveedor` ASC);

CREATE INDEX `fk_proveedor_sucursal_comuna1_idx` ON `proveedor_sucursal` (`id_comuna` ASC);

CREATE UNIQUE INDEX `idx_proveedor_sucursal_descripcion` USING BTREE ON `proveedor_sucursal` (`descripcion` ASC);


-- -----------------------------------------------------
-- Table `oferta_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oferta_cotizacion` (
  `id_oferta_cotizacion` BIGINT NOT NULL AUTO_INCREMENT,
  `id_proveedor_sucursal` INT NOT NULL,
  `id_cotizacion` BIGINT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comentarios` TEXT NULL,
  PRIMARY KEY (`id_oferta_cotizacion`),
  CONSTRAINT `fk_oferta_cotizacion_cotizacion1`
    FOREIGN KEY (`id_cotizacion`)
    REFERENCES `cotizacion` (`id_cotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oferta_cotizacion_proveedor_sucursal1`
    FOREIGN KEY (`id_proveedor_sucursal`)
    REFERENCES `proveedor_sucursal` (`id_proveedor_sucursal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_oferta_cotizacion_cotizacion1_idx` ON `oferta_cotizacion` (`id_cotizacion` ASC);

CREATE INDEX `fk_oferta_cotizacion_proveedor_sucursal1_idx` ON `oferta_cotizacion` (`id_proveedor_sucursal` ASC);


-- -----------------------------------------------------
-- Table `marca_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marca_proveedor` (
  `id_marca_proveedor` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  `certificado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_marca_proveedor`),
  CONSTRAINT `fk_marca_proveedor_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marca_proveedor_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_marca_proveedor_marca1_idx` ON `marca_proveedor` (`id_marca` ASC);

CREATE INDEX `fk_marca_proveedor_proveedor1_idx` ON `marca_proveedor` (`id_proveedor` ASC);


-- -----------------------------------------------------
-- Table `usuario_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_web` (
  `id_usuario_web` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(16) NOT NULL,
  `contrasena` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(16) NOT NULL,
  `apellidos` VARCHAR(32) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `activo` BIT(1) NOT NULL DEFAULT b'0',
  `borrado` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id_usuario_web`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `idx_usuario_web_nombre_usuario` USING BTREE ON `usuario_web` (`nombre_usuario` ASC);

CREATE UNIQUE INDEX `idx_usuario_web_email` USING BTREE ON `usuario_web` (`email` ASC);


-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rol` (
  `id_rol` SMALLINT NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedor_sucursal_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_sucursal_usuario` (
  `id_proveedor_sucursal_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor_sucursal` INT NOT NULL,
  `id_usuario` BIGINT NOT NULL,
  `id_rol` SMALLINT NOT NULL,
  `rut` VARCHAR(15) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`id_proveedor_sucursal_usuario`),
  CONSTRAINT `fk_proveedor_sucursal_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_usuario_proveedor_sucursal1`
    FOREIGN KEY (`id_proveedor_sucursal`)
    REFERENCES `proveedor_sucursal` (`id_proveedor_sucursal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_sucursal_usuario_usuario1_idx` ON `proveedor_sucursal_usuario` (`id_usuario` ASC);

CREATE INDEX `fk_proveedor_sucursal_usuario_proveedor_sucursal1_idx` ON `proveedor_sucursal_usuario` (`id_proveedor_sucursal` ASC);

CREATE INDEX `fk_proveedor_sucursal_usuario_rol1_idx` ON `proveedor_sucursal_usuario` (`id_rol` ASC);


-- -----------------------------------------------------
-- Table `medio_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medio_pago` (
  `id_medio_pago` SMALLINT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medio_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura` (
  `folio` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  `id_medio_pago` SMALLINT NOT NULL,
  `numero_tx` VARCHAR(32) NULL,
  `detalle_pago` VARCHAR(256) NULL,
  `pagada` TINYINT(1) NULL,
  PRIMARY KEY (`folio`),
  CONSTRAINT `fk_factura_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_medio_pago1`
    FOREIGN KEY (`id_medio_pago`)
    REFERENCES `medio_pago` (`id_medio_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_factura_proveedor1_idx` ON `factura` (`id_proveedor` ASC);

CREATE INDEX `fk_factura_medio_pago1_idx` ON `factura` (`id_medio_pago` ASC);


-- -----------------------------------------------------
-- Table `adjudicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adjudicacion` (
  `id_adjudicacion` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cotizacion` BIGINT NOT NULL,
  `id_oferta_cotizacion` BIGINT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comentarios` TEXT NULL,
  PRIMARY KEY (`id_adjudicacion`),
  CONSTRAINT `fk_adjudicacion_cotizacion1`
    FOREIGN KEY (`id_cotizacion`)
    REFERENCES `cotizacion` (`id_cotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjudicacion_oferta_cotizacion1`
    FOREIGN KEY (`id_oferta_cotizacion`)
    REFERENCES `oferta_cotizacion` (`id_oferta_cotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_adjudicacion_cotizacion1_idx` ON `adjudicacion` (`id_cotizacion` ASC);

CREATE INDEX `fk_adjudicacion_oferta_cotizacion1_idx` ON `adjudicacion` (`id_oferta_cotizacion` ASC);


-- -----------------------------------------------------
-- Table `proveedor_sucursal_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_sucursal_servicio` (
  `id_proveedor_sucursal_servicio` BIGINT NOT NULL AUTO_INCREMENT,
  `id_proveedor_sucursal` INT NOT NULL,
  `id_servicio` INT NOT NULL,
  `id_tipo_vehiculo` SMALLINT NOT NULL,
  PRIMARY KEY (`id_proveedor_sucursal_servicio`),
  CONSTRAINT `fk_proveedor_sucursal_servicio_proveedor_sucursal1`
    FOREIGN KEY (`id_proveedor_sucursal`)
    REFERENCES `proveedor_sucursal` (`id_proveedor_sucursal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_servicio_servicio1`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_servicio_tipo_vehiculo1`
    FOREIGN KEY (`id_tipo_vehiculo`)
    REFERENCES `tipo_vehiculo` (`id_tipo_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_sucursal_servicio_proveedor_sucursal1_idx` ON `proveedor_sucursal_servicio` (`id_proveedor_sucursal` ASC);

CREATE INDEX `fk_proveedor_sucursal_servicio_servicio1_idx` ON `proveedor_sucursal_servicio` (`id_servicio` ASC);

CREATE INDEX `fk_proveedor_sucursal_servicio_tipo_vehiculo1_idx` ON `proveedor_sucursal_servicio` (`id_tipo_vehiculo` ASC);


-- -----------------------------------------------------
-- Table `proveedor_sucursal_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_sucursal_marca` (
  `id_proveedor_sucursal_marca` BIGINT NOT NULL AUTO_INCREMENT,
  `id_proveedor_sucursal` INT NOT NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`id_proveedor_sucursal_marca`),
  CONSTRAINT `fk_proveedor_sucursal_marca_proveedor_sucursal1`
    FOREIGN KEY (`id_proveedor_sucursal`)
    REFERENCES `proveedor_sucursal` (`id_proveedor_sucursal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_marca_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_sucursal_marca_proveedor_sucursal1_idx` ON `proveedor_sucursal_marca` (`id_proveedor_sucursal` ASC);

CREATE INDEX `fk_proveedor_sucursal_marca_marca1_idx` ON `proveedor_sucursal_marca` (`id_marca` ASC);


-- -----------------------------------------------------
-- Table `proveedor_sucursal_combustible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_sucursal_combustible` (
  `id_proveedor_sucursal_combustible` BIGINT NOT NULL AUTO_INCREMENT,
  `id_combustible` SMALLINT NOT NULL,
  `id_proveedor_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_proveedor_sucursal_combustible`),
  CONSTRAINT `fk_proveedor_sucursal_combustible_combustible1`
    FOREIGN KEY (`id_combustible`)
    REFERENCES `combustible` (`id_combustible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_sucursal_combustible_proveedor_sucursal1`
    FOREIGN KEY (`id_proveedor_sucursal`)
    REFERENCES `proveedor_sucursal` (`id_proveedor_sucursal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_sucursal_combustible_combustible1_idx` ON `proveedor_sucursal_combustible` (`id_combustible` ASC);

CREATE INDEX `fk_proveedor_sucursal_combustible_proveedor_sucursal1_idx` ON `proveedor_sucursal_combustible` (`id_proveedor_sucursal` ASC);


DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER `cotizacion_BEFORE_INSERT` BEFORE INSERT ON `cotizacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_creacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `cotizacion_BEFORE_UPDATE` BEFORE UPDATE ON `cotizacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_modificacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `proveedor_BEFORE_INSERT` BEFORE INSERT ON `proveedor` FOR EACH ROW
BEGIN
    SET NEW.fecha_creacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `proveedor_sucursal_BEFORE_INSERT` BEFORE INSERT ON `proveedor_sucursal` FOR EACH ROW
BEGIN
    SET NEW.fecha_creacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `oferta_cotizacion_BEFORE_INSERT` BEFORE INSERT ON `oferta_cotizacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_creacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `oferta_cotizacion_BEFORE_UPDATE` BEFORE UPDATE ON `oferta_cotizacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_modificacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `adjudicacion_BEFORE_INSERT` BEFORE INSERT ON `adjudicacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_creacion = CURRENT_TIMESTAMP;
END$$

CREATE DEFINER = CURRENT_USER TRIGGER `adjudicacion_BEFORE_UPDATE` BEFORE UPDATE ON `adjudicacion` FOR EACH ROW
BEGIN
    SET NEW.fecha_modificacion = CURRENT_TIMESTAMP;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
